/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/resources/views/layout/*.{pug, html}",
    "./src/resources/views/customer/*.{pug, html}",
    "./src/resources/views/shipper/*.{pug, html}",
    "./src/resources/views/menu/*.{pug, html}",
    "./src/resources/views/order/*.{pug, html}",
    "./src/resources/views/auth/*.{pug, html}",
    "./src/resources/views/*.{pug, html}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-grey": "#F7F6F9",
        "dark-grey": "#8A8B95",
        "primary-dark": "#575663",
        "light-purple": "#EFE9FF",
        "strong-purple": "#6324FE",
        primary: {
          50: "#f5f3ff",
          100: "#ede9fe",
          200: "#ddd6fe",
          300: "#c4b5fd",
          400: "#a78bfa",
          500: "#8b5cf6",
          600: "#7c3aed",
          700: "#6d28d9",
          800: "#5b21b6",
          900: "#4c1d95",
        },
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [],
};
